config/routes.rb
AddictedToIan::Application.routes.draw do

  devise_for :users

  match '/contact' => 'contact#index', :as => :contact
  match '/about' => 'about#index', :as => :about
  match '/resume' => 'about#resume', :as => :resume
  match '/rss.xml' => 'blogs#rss', :as => :blog_rss

  resources :blogs do |blogs|
    collection do
      get :tweets
    end
  end

  resources :blog_photos

  match '/blogs/search/:by/:year/:month/:day' => 'blogs#search', :as => :blog_calendar_day
  match '/blogs/search/:by' => 'blogs#search', :as => :blog_search
  match '/blog/new_photo_field' => 'blogs#new_photo_field', :as => :blog_new_photo_field
  match '/pictures' => 'pictures#index', :as => :pictures
  match '/pictures/album/:id' => 'pictures#album', :as => :pictures_album
  match '/pictures/photo/:id' => 'pictures#photo', :as => :pictures_album

  resources :albums

  match '/albums/new_photo_field' => 'albums#new_photo_field', :as => :new_photo_field

  resources :photos
  resources :plugs

  match '/links/category/:category' => 'links#index', :as => :link_category

  resources :links

  root :to => 'blogs#index'

end

app/models/blog.rb
# == Schema Information
# Schema version: 20090501023904
#
# Table name: blogs
#
#  id         :integer(4)      not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Blog < ActiveRecord::Base

  acts_as_taggable
  has_many :blog_photos, :dependent => :destroy
  after_save :save_attachments

  def photo_by_filename(filename)
    blog_photos.each do |blog_photo|
      return blog_photo if blog_photo.filename == filename
    end
    nil
  end

  def next
    self.class.first(:conditions => [ 'created_at > ?', created_at ], :order => 'created_at ASC')
  end
  
  def previous
    self.class.first(:conditions => [ 'created_at < ?', created_at ], :order => 'created_at DESC')
  end
  
  def self.for_month(year, month)
    start_time = DateTime.civil(year, month)
    end_time   = DateTime.civil(year, month, days_in_month(year, month), 23, 59, 59)
    all(:conditions => [ 'created_at > ? AND created_at < ?', start_time, end_time ] )
  end
  
  def self.for_day(year, month, day)
    start_time = DateTime.civil(year, month, day)
    end_time   = DateTime.civil(year, month, day, 23, 59, 59)
    all(:conditions => [ 'created_at > ? AND created_at < ?', start_time, end_time ] )
  end
  
  def attachable=(params)
    @attachments = params.keys.sort.inject([]) { |vals, k| vals.push(params[k]) }.reject {|a| a[:uploaded_data].blank? }.collect { |a| BlogPhoto.new(a) }
  end
  
  def image_replaced_content
    content.gsub(/#\{img:\s*(.*)\s+(\S*)\}/) do |match|
      logger.debug("matched = #{match}, #{$1}, #{$2}")      
      if !(photo = photo_by_filename($1))
        ''
      else
        "<p style = \"text-align: #{$2}\"><img src = \"#{photo.public_filename}\"  style = \"float: none\" /></p>"
      end
    end
  end
  
  protected
  def self.days_in_month(year, month)
    (Date.new(year, 12, 31) << (12-month)).day
  end
  
  def save_attachments
    if @attachments
      @attachments.each do |attachment|
        blog_photos << attachment
      end
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :load_blog,     :only => [ :index, :show, :destroy, :update ]
  before_filter :load_calendar, :only => [ :index, :show ]

  def index
    render :action => :show
  end

  def rss
    @blogs = Blog.all(:order => 'created_at DESC', :limit => 5)
    render :layout => false
  end

  def show; end

  def create
    @blog = Blog.new(params[:blog])
    if @blog.save
      flash[:notice] = 'Blog was successfully created.'
      redirect_to(@blog)
    else
      render :action => "new"
    end
  end

  def update
    if @blog.update_attributes(params[:blog])
      flash[:notice] = 'Blog was successfully updated.'
      redirect_to(@blog)
    else
      render :action => "edit"
    end
  end
  
  def new_photo_field
    render :partial => 'blog_photo_fields', :locals => { :num => params[:num] }
  end

  def destroy
    @blog.destroy
    redirect_to(blogs_url)
  end
  
  def search
    @by = params[:by]
    @value = params[:value]
    @blogs = case @by
     when 'tag': Blog.find_tagged_with(@value)
     when 'keyword': Blog.all(:conditions => [ 'LOWER(title) LIKE ? OR LOWER(content) LIKE ?', "%#{@value}%", "%#{@value}%"] )
     when 'date': Blog.for_day(params[:year].to_i, params[:month].to_i, params[:day].to_i)
     else []
    end
    
    if @blogs.size == 1
      @blog = @blogs.first
      load_calendar
      render :action => :show and return
    end
    
    load_calendar
  end

  def tweets
    render :layout => false
  end
  
  protected
  def load_blog
    if params[:id]
      @blog = Blog.find(params[:id])
    else
      @blog = Blog.last
    end
  end
  
  def load_calendar
    @year  = params[:yr] ? params[:yr].to_i : (@blog ? @blog.created_at.year  : Date.today.year)
    @month = params[:mo] ? params[:mo].to_i : (@blog ? @blog.created_at.month : Date.today.month)
    @previous = { :year => @month == 1  ? @year - 1 : @year, :month => @month == 1  ? 12 : @month - 1 }
    @next     = { :year => @month == 12 ? @year + 1 : @year, :month => @month == 12 ? 1  : @month + 1 }
    
    @selected_days = Blog.for_month(@year, @month).collect { |b| b.created_at.mday }.uniq
  end
  
end

app/helpers/blog_helper.rb
module BlogHelper

  def render_calendar(year, month, pre, nex, selected_days)
    previous_month = link_to("<<", params.merge({:mo => pre[:month], :yr => pre[:year] }))
    next_month     = link_to(">>", params.merge({:mo => nex[:month], :yr => nex[:year] }))
    calendar(
        :year                => year,
        :month               => month,
        :abbrev              => (0..0),
        :previous_month_text => previous_month,
        :next_month_text     => next_month,
        :month_name_class    => 'month_name',
        :month_nav_class     => 'month_nav') do |d|
      if selected_days.include?(d.mday)
        day_display = link_to(d.mday.to_s, blog_calendar_day_path(:by => 'date', :year => year, :month => month, :day => d.mday))
      else
        day_display = d.mday.to_s
      end
      [ day_display, { :class => selected_days.include?(d.mday) ? 'specialDay' : 'day' } ]
    end
  end
end

app/views/blogs/_blog_photo.haml
.blog_photo_edit
  = image_tag(blog_photo.public_filename)
  %strong= link_to 'Delete Photo', blog_photo_path(blog_photo), :method => :delete, :confirm => 'Are you sure?'
  %br/
  To include in your blog, use the following text: \#{img:#{blog_photo.filename} [align]} where align = left, right or center
.clear

app/views/blogs/_blog_photo_fields.haml
.new_photo
  %label File:
  = file_field_tag("blog[attachable][#{num}][uploaded_data]", :size => 60)
  .clear

app/views/blogs/_form.haml
:javascript
  var num_photos = 1;
  function add_photo_field() {
    num_photos++;
     #{remote_function(:url => { :action => 'new_photo_field' }, :with => "'num=' + num_photos", :update => "new_photos_\#{obj.id}", :position => :before)}
  }
= form_for(obj, :html => { :multipart => true }) do |f|
  = f.error_messages
  = link_to_function 'cancel', "toggle('#{div}')", :class => 'admin_link', :style => 'float: right'
  %h4 Title:
  .clear
  = f.text_field :title
  .clear
  %h4 Content:
  .clear
  = f.text_area :content, :rows => 30, :cols => 80
  .clear
  %h4 Tags:
  .clear
  = f.text_field :tag_list, :size => 90
  .clear
  = render :partial => 'blog_photo_fields', :locals => { :num => 1 }
  - if obj.blog_photos.size > 0
    .edit_photos
      - obj.blog_photos.each do |blog_photo|
        = render :partial => 'blog_photo', :object => blog_photo
  .new_photos_entry{:id => "new_photos_#{obj.id}"}
    = f.submit "Save"
    = link_to_function('+ Add Another Photo', "add_photo_field()")

app/views/blogs/_widgets.haml
#widgets
  - [ 'twitter', 'posts', 'search' ].each do |widget|
    .widget
      %h3= widget.humanize.downcase
      = render :partial => "widgets/blogs/#{widget}"

app/views/blogs/search.haml
#blog_display.main_content
  %p.light
    %strong= @blogs.size
    blog entries were
    - if @by == 'tag'
      found tagged with
      %strong
        "#{@value}."
    - elsif @by == 'keyword'
      found containing text
      %strong
        "#{@value}."
    - elsif @by == 'date'
      created on
      %strong= Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i).strftime('%B %d, %Y')
  .clear
  - @blogs.each_with_index do |blog, num|
    .search_result
      .result_num
        = num + 1
        \.
      %h4= link_to(highlight(blog.title, @value), blog_path(blog))
      .clear
      %p.result_preview
        - if @by == 'keyword'
          != highlight(excerpt(markdown(blog.image_replaced_content).gsub(/<\/?[^>]*>/, ''), @value, :radius => 50), @value)
        - else
          != truncate(markdown(blog.image_replaced_content).gsub(/<\/?[^>]*>/, ''), :length => 200)
        .clear
- content_for :widgets do
  = render :partial => 'widgets'

app/views/blogs/show.haml
- if user_signed_in?
  :javascript
    function toggle(div) {
      $('#blog_display').toggle();
      $('#' + div).toggle();
      Application.cufonize();
    }

- if !@blog
  - if user_signed_in?
    #blog_create.main_content
      = render :partial => 'form', :locals => { :obj => Blog.new, :div => 'blog_create' }
- else
  #blog_display.main_content
    %h3#blog_title= @blog.title
    - if user_signed_in?
      .clear
      = link_to_function 'edit',   "toggle('blog_edit')", :class => 'admin_link'
      = link_to_function 'create', "toggle('blog_create')", :class => 'admin_link'
      = link_to 'delete', blog_path(@blog), :method => :delete, :confirm => 'Are you sure?', :class => 'admin_link'
    .clear
    .blog_text
      != markdown(@blog.image_replaced_content)
    .blog_nav
      - if prev = @blog.previous
        = link_to(image_tag('button_left.jpg', :class => 'previous'), blog_path(prev))
        .previous= link_to(truncate(prev.title, :length => 30), blog_path(prev))
      - if nxt = @blog.next
        = link_to(image_tag('button_right.jpg', :class => 'next'), blog_path(nxt))
        .next= link_to(truncate(nxt.title, :length => 30), blog_path(nxt))
  - if user_signed_in?
    #blog_edit.main_content{:style => "display: none"}
      = render :partial => 'form', :locals => { :obj => @blog, :div => 'blog_edit' }
    #blog_create.main_content{:style => "display: none"}
      = render :partial => 'form', :locals => { :obj => Blog.new, :div => 'blog_create' }
  - content_for :widgets do
    = render :partial => 'widgets'

app/views/blogs/tweets.haml
- begin
  - Twitter.user_timeline('ianenders', :count => 4).each do |status|
    .tweet
      %strong
        = link_to(status.user.screen_name, "http://www.twitter.com/#{status.user.screen_name}")
        \:
      != twitter_text(status.text)
      %br/
      %span.tweet_info
        = twitter_time(Time.parse(status.created_at))
        from #{status.source}
- rescue Exception => e
  - logger.warn e.inspect
  .tweet Unable to load tweets.