config/routes.rb
AddictedToIan::Application.routes.draw do

  devise_for :users

  match '/contact' => 'contact#index', :as => :contact
  match '/about' => 'about#index', :as => :about
  match '/resume' => 'about#resume', :as => :resume
  match '/rss.xml' => 'blogs#rss', :as => :blog_rss

  resources :blogs do |blogs|
    collection do
      get :tweets
    end
  end

  resources :blog_photos

  match '/blogs/search/:by/:year/:month/:day' => 'blogs#search', :as => :blog_calendar_day
  match '/blogs/search/:by' => 'blogs#search', :as => :blog_search
  match '/blog/new_photo_field' => 'blogs#new_photo_field', :as => :blog_new_photo_field
  match '/pictures' => 'pictures#index', :as => :pictures
  match '/pictures/album/:id' => 'pictures#album', :as => :pictures_album
  match '/pictures/photo/:id' => 'pictures#photo', :as => :pictures_album

  resources :albums

  match '/albums/new_photo_field' => 'albums#new_photo_field', :as => :new_photo_field

  resources :photos
  resources :plugs

  match '/links/category/:category' => 'links#index', :as => :link_category

  resources :links

  root :to => 'blogs#index'

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @albums = Album.all(:order => 'created_at DESC')
  end
  
  def album
    render :partial => 'album', :object => Album.find(params[:id]), :locals => { :num_image_rows => params[:num_image_rows].to_i }
  end

end

app/views/pictures/_album.haml
- if album
  - partitioned_gallery = []
  - (0..album.size - 1).step(5) {|i| partitioned_gallery.push(album.photos.sort{|a, b| (a.position || 0) <=> (b.position || 0) }[i..i + 4]) }
  - partitioned_gallery.each_with_index do |row, i|
    .thumbs{:id => "thumbs_row_#{i}", :style => i >= num_image_rows ? 'display: none' : ''}
      - row.each do |photo|
        .gallery_image{:rel => photo.id}
          = image_tag(photo.thumb_url,
              :width  => photo.thumb_width,
              :height => photo.thumb_height,
              :style  => "height: #{photo.thumb_height}px; width: #{photo.thumb_width}px")
        %div{:id => "photo_filename_#{photo.id}", :style => "display: none"}= photo.public_filename
        %div{:id => "photo_height_#{photo.id}", :style => "display: none"}= photo.height
        %div{:id => "photo_width_#{photo.id}", :style => "display: none"}= photo.width
        %div{:id => "photo_data_#{photo.id}", :style => "display: none"}
          - if photo.title
            %h3= photo.title
          - if photo.description
            %h4= photo.description
          .file_info
            file:
            %strong= photo.filename
          .date_info
            - if photo.tag('CreateDate')
              taken:
              %strong= photo.tag('CreateDate')
              %br/
          .exif
            %ul
              - if photo.tag('Model')
                %li
                  %strong
                    model: #{photo.tag('Model')}
            %ul
              - if photo.tag('Aperture')
                %li
                  aperture:
                  %strong= photo.tag('Aperture')
              - if photo.tag('FocalLength')
                %li
                  focal length:
                  %strong= photo.tag('FocalLength')
              - if photo.tag('ISO')
                %li
                  iso:
                  %strong= photo.tag('ISO')
              - if photo.tag('ShutterSpeed')
                %li
                  shutter:
                  %strong= photo.tag('ShutterSpeed')
              - if photo.tag('Flash')
                %li
                  flash:
                  %strong= photo.tag('Flash')
              - if photo.tag('MeteringMode')
                %li
                  metering:
                  %strong= photo.tag('MeteringMode')
    .clear
    
  :javascript
    $(function() {
      num_image_rows = #{partitioned_gallery.size};
    
      // Hide top and bottom nav arrows if we don't need them.
      $('#forward_images').#{partitioned_gallery.size <= num_image_rows ? 'fadeOut' : 'fadeIn'}("slow");
      $('#back_images').#{partitioned_gallery.size <= num_image_rows ? 'fadeOut' : 'fadeIn'}("slow");
    
      // Reset top/bottom arrows to the proper state for greyed out / not greyed
      $('#back_images').css('background-color', '#DDDDDD');
      $('#back_images').find('img').fadeOut();
      $('#forward_images').css('background-color', 'white');
      $('#forward_images').find('img').fadeIn();
    
      // Center the thumbnails vertically in their container.
      $('.gallery_image').each(function() {
        $(this).find('img').css('margin-top', (parseInt($(this).css('height')) - parseInt($(this).find('img').css('height'))) / 2);
      });

      // Select the first image in the gallery.
      $('.gallery_image:first').click();
    
      // Reset our position in the gallery to what is visible on first load.
      image_row_first = 0;
      image_row_last = #{num_image_rows - 1};
    });
  

app/views/pictures/index.haml
- content_for :head do
  = javascript_include_tag 'gallery'

.album_nav{'data-size' => @albums.size}
  .albums
    #back_album.arrows
      %img{:alt => "top", :src => "/images/arrow_top.png", :style => "display: none"}
    - @albums.each_with_index do |album, i|
      .album_data{:id => "album_#{i}", :style => i >= 4 ? 'display: none' : ''}    
        %a.album_link{:href => "#", :rel => album.id}= image_tag(album.cover_photo_url)
        %h4
          = album.name
          - if user_signed_in?
            .admin_links
              = link_to 'edit',   edit_album_path(album)
              \&nbsp;&nbsp;
              = link_to 'delete', album_path(album), :method => :delete, :confirm => 'Are you sure?'
        %h5
          = album.date
          %br/
          = album.size
          image#{album.size == 1 ? '' : 's'}
    #forward_album.arrows.no_border
      %img{:alt => "bottom", :src => "/images/arrow_bottom.png"}/
      
.thumb_wrapper
  #back_images.thumb_arrows{:style => "display: none"}
    %img{:alt => "top", :src => "/images/arrow_top.png"}/
  #thumb_area
    = render :partial => 'album', :object => @albums.first, :locals => { :num_image_rows => 4 }
  #forward_images.thumb_arrows{:style => "display: none"}
    %img{:alt => "bottom", :src => "/images/arrow_bottom.png"}/
.pictures
  #image_loading{:style => "display: none"}= image_tag('gallery-loading.gif')
  #picture
    - if @albums.first && @albums.first.photos.first
      = image_tag(@albums.first.photos.first.public_filename)
- if user_signed_in?
  .clear
  .new_album_link
    = link_to('Create New Album', new_album_path)