config/routes.rb
AddictedToIan::Application.routes.draw do

  devise_for :users

  match '/contact' => 'contact#index', :as => :contact
  match '/about' => 'about#index', :as => :about
  match '/resume' => 'about#resume', :as => :resume
  match '/rss.xml' => 'blogs#rss', :as => :blog_rss

  resources :blogs do |blogs|
    collection do
      get :tweets
    end
  end

  resources :blog_photos

  match '/blogs/search/:by/:year/:month/:day' => 'blogs#search', :as => :blog_calendar_day
  match '/blogs/search/:by' => 'blogs#search', :as => :blog_search
  match '/blog/new_photo_field' => 'blogs#new_photo_field', :as => :blog_new_photo_field
  match '/pictures' => 'pictures#index', :as => :pictures
  match '/pictures/album/:id' => 'pictures#album', :as => :pictures_album
  match '/pictures/photo/:id' => 'pictures#photo', :as => :pictures_album

  resources :albums

  match '/albums/new_photo_field' => 'albums#new_photo_field', :as => :new_photo_field

  resources :photos
  resources :plugs

  match '/links/category/:category' => 'links#index', :as => :link_category

  resources :links

  root :to => 'blogs#index'

end

app/models/plug.rb
# == Schema Information
# Schema version: 20090501023904
#
# Table name: plugs
#
#  id            :integer(4)      not null, primary key
#  plug_photo_id :integer(4)
#  title         :string(255)
#  description   :text
#  url           :string(255)
#

class Plug < ActiveRecord::Base
  belongs_to :plug_photo, :dependent => :destroy
  after_save :save_attachments
    
  def attachable=(params)
    @attachments = params.keys.sort.inject([]) { |vals, k| vals.push(params[k]) }.reject {|a| a[:uploaded_data].blank? }.collect { |a| PlugPhoto.new(a) }
  end
  
  protected
  def save_attachments
    if @attachments && @attachments.first
      @attachments.first.save
      if plug_photo_id != @attachments.first.id
        update_attribute(:plug_photo_id, @attachments.first.id)
      end
    end
  end
end

app/controllers/plugs_controller.rb
class PlugsController < ApplicationController

  before_filter :load_plug, :only => [ :edit, :update, :destroy ]
  
  def index
    @plugs = Plug.all(:order => 'created_at DESC')
  end

  def edit;  end

  def create
    @plug = Plug.new(params[:plug])
    if @plug.save
      flash[:notice] = 'Plug was successfully created.'
      redirect_to(:action => 'index')
    else
      render :action => "index"
    end
  end

  def update
    if @plug.update_attributes(params[:plug])
      flash[:notice] = 'Plug was successfully updated.'
      redirect_to(:action => 'index')
    else
      render :action => "index"
    end
  end
  
  def destroy
    @plug.destroy
    redirect_to(:action => 'index')
  end
  
  protected
  def load_plug
    @plug = Plug.find(params[:id])
  end
  
end

app/views/plugs/_form.haml
- form_for(obj, :html => { :multipart => true }) do |f|
  = f.error_messages
  %h4 Title:
  %p= f.text_field :title
  %h4 URL:
  %p= f.text_field :url
  %h4 Description:
  %p= f.text_area :description, :rows => 30, :cols => 80
  %h4 Image:
  %p= file_field_tag("plug[attachable][0][uploaded_data]", :size => 60)
  = f.submit "Save"

app/views/plugs/edit.haml
.main_content
  %h3
    Edit Plug: #{@plug.title}
  .clear
  = render :partial => 'form', :locals => { :obj => @plug }

app/views/plugs/index.haml
- content_for :head do
  = javascript_include_tag 'plugs'

.plugs_content
  .plug_thumb_wrapper
    .thumb_slider
      - @plugs.each_with_index do |plug, i|
        .thumb_holder{:id => "plug_#{i}", :rel => i}
          = link_to(image_tag(plug.plug_photo.public_filename(:thumb)), '#')
          .large_img{:style => "display: none"}= plug.plug_photo.public_filename
          .plug_title_overlay
            %span{:style => "display: none"}= plug.title
  = image_tag('arrow_top.png', :class => 'row_nav prev_row', :style => 'display: none')
  = image_tag('arrow_bottom.png', :class => 'row_nav next_row', :style => 'display: none')
  - @plugs.each_with_index do |plug, i|
    .plug{:id => "plug_main_#{i}", :style => "display: none"}
      = image_tag("button_close.gif", :class => 'close', :style => 'display: none')
      = image_tag(plug.plug_photo.public_filename, :style => 'display: none')
      .plug_link_holder{:style => "display: none"}
        [ #{link_to(plug.url, 'http://' + plug.url)} ]
      .plug_description_holder
        %h3= plug.title
        - if user_signed_in?
          .admin_links
            = link_to('edit', edit_plug_path(plug))
            \&nbsp;&nbsp;
            \#{link_to('delete', plug_path(plug), :method => :delete, :confirm => 'Are you sure?')}
        .clear
        .plug_text{:style => "display: none"}
          != markdown(plug.description)
- if user_signed_in?
  .new_plug_link= link_to 'New Plug', new_plug_path

app/views/plugs/new.haml
.main_content
  %h3 New Plug
  .clear
  = render :partial => 'form', :locals => { :obj => Plug.new }